### ISSUE TITLE
Webinar 1: dead link

### ISSUE THREAD

**Issue by norsimon** [kreshuklab/teaching-dl-course-2022#1]
Introduction to Python for Data Science - basic

https://www.edx.org/course/introduction-to-python-for-data-science-2

Gives 404 error.

Cheers,
Simon

**Comment by constantinpape** [comment]
Thanks for checking this! I had copied these recommendations from our earlier course and looks like the link is no longer valid.
I removed it in e52d81f.

Feel free to propose more suitable additional material for Webinar 1 or 2..

**Comment by norsimon** [comment]
Well, that was fast!

Thank you & I will if I think of something.

**Comment by norsimon** [comment]
For learning Python for image analysis (webinar 1)
Here is recent resource from Guillaume Witz: Video and notebooks for Python from NEUBIAS:
Part 1: https://www.youtube.com/watch?v=2KF8vBrp3Zw&t=0s
Part 2: https://www.youtube.com/watch?v=Y3pB3wnOivE&t=0s
Forum Q&A: https://forum.image.sc/t/neubias-academy-home-webinar-interactive-bioimage-analysis-with-python-and-jupyter-questions-answers/37596
Slides: https://docs.google.com/presentation/d/1N1ikhtEscuviINAnqUXnUSRS-Gz9sp-0bX8IO_ecW3E/edit
Notebooks: https://github.com/guiwitz/neubias_academy_biapy

**Comment by constantinpape** [comment]
Thanks! I have added it to the additional material.
